package com.kai.composeanimelist.model

import com.kai.composeanimelist.R

object AnimeData {
    val animes = listOf(
        Anime(1,"Tate No Yuusha", R.drawable.tate, "After defeating the Spirit Tortoise, Naofumi has no time for rest. An attack from the next Guardian Beast is imminent, but the three other Cardinal Heroes have gone missing. So, Naofumi and his party set out to search for the legendary trio."),
        Anime(2, "Kage No Jitsuryokusha Ni Naritakute", R.drawable.kage, "Everything has been going according to plan, but the hour of awakening draws near. Cid Kagenou and Shadow Garden investigate the Lawless City, a cesspool where the red moon hangs low in the sky and three powerful monarchs rule the streets. The true draw for Cid, however, is one who can draw blood–the Blood Queen, a vampire who has slumbered in her coffin for eons. Her awakening approaches, and Cid could finally face a day of reckoning."),
        Anime(3, "Tensei Shitara Slime", R.drawable.tensura, "That Time I Got Reincarnated as a Slime, also known as Regarding Reincarnated to Slime and by the contraction TenSura, is a Japanese fantasy light novel series written by Fuse, and illustrated by Mitz Vah."),
        Anime(4, "Fate/Zero", R.drawable.fatezero, "Fate/Zero is set ten years before the events of Fate/stay night, and tells the story of the Fourth Holy Grail War, a secret magical tournament held in Fuyuki City, Japan, where seven mages known as Masters summon Servants, reincarnations of legendary souls and heroes from all across time, where they fight in a deadly battle royale where the winner obtains the Holy Grail, a legendary magical chalice capable of granting wishes. The main protagonist, Kiritsugu Emiya, the foster father of Fate/stay night's protagonist, Shirou Emiya, is known as a ruthless assassin who joins the tournament on behalf of his wife's family, the Einzberns."),
        Anime(5, "Fate Strange Fake", R.drawable.strange, "In the American city of Snowfield, a new Holy Grail War is about to erupt. Such ruthless confrontations pit against each other magic experts known as magi, who ascend to the status of Master by summoning Servants—heroic spirits of the past. The winner is thought to have any one of their wishes granted.\n" +
                "\n" +
                "However, it appears that the organization behind the present situation has merely managed to create an imperfect copy of the Third Holy Grail War. As the unusual ritual catches the attention of the Mage's Association in London, Flatt Escardos, the young apprentice of Lord El-Melloi II—a former participant of the Fourth Holy Grail War—travels to Snowfield and, to the great dismay of his teacher, joins the ranks of the Masters.\n" +
                "\n" +
                "In this fake conflict where the line between Masters and Servants is blurred, the different factions will have a hard time preventing the city of Snowfield from plunging into total chaos."),
        Anime(6, "Fate Grand Order/Solomon", R.drawable.fgo, "After battling their way through all seven Singularities, the Chaldea Security Organization has finally arrived at the endpoint of the Grand Order: The Final Singularity, Grand Temple of Time: Solomon. Now is the time to defeat the root of all evil, Solomon, the King of Mages. Now is the time to reclaim the future. With the final operation looming large, Romani Archaman considers the choices he will soon have to make, Mash Kyrielight dwells on life's limitations, and Fujimaru prepares to receive a new Mystic Code. All their many encounters have led to this moment as Fujimaru and Mash at last embark on their final operation..."),
        Anime(7, "Sword Art Online", R.drawable.sao, "Ever since the release of the innovative NerveGear, gamers from all around the globe have been given the opportunity to experience a completely immersive virtual reality. Sword Art Online (SAO), one of the most recent games on the console, offers a gateway into the wondrous world of Aincrad, a vivid, medieval landscape where users can do anything within the limits of imagination. With the release of this worldwide sensation, gaming has never felt more lifelike.\n" +
                "\n" +
                "However, the idyllic fantasy rapidly becomes a brutal nightmare when SAO's creator traps thousands of players inside the game. The \"log-out\" function has been removed, with the only method of escape involving beating all of Aincrad's one hundred increasingly difficult levels. Adding to the struggle, any in-game death becomes permanent, ending the player's life in the real world.\n" +
                "\n" +
                "While Kazuto \"Kirito\" Kirigaya was fortunate enough to be a beta-tester for the game, he quickly finds that despite his advantages, he cannot overcome SAO's challenges alone. Teaming up with Asuna Yuuki and other talented players, Kirito makes an effort to face the seemingly insurmountable trials head-on. But with difficult bosses and threatening dark cults impeding his progress, Kirito finds that such tasks are much easier said than done."),
        Anime(8,"Guilty Crown", R.drawable.gc, "On December 24, 2029—the day colloquially known as the \"Lost Christmas\"—the Apocalypse Virus spread across Japan, bringing death to its citizens and plunging the country into utter chaos. In an effort to establish order, the United Nations sends the GHQ to assist with the crisis by containing the outbreak while removing all political autonomy in the process. A decade later, the country still lives under their control, unable to break free from their draconian rule.\n" +
                "\n" +
                "Frustrated with the state of the nation, a resistance group named the Funeral Parlor aims to liberate Japan from the GHQ. Led by the charismatic Gai Tsutsugami, the group plots to steal a vial containing the \"Void Genome\" to further their goals. The vial falls into the hands of internet vocalist Inori Yuzuriha, who ends up being hunted by the GHQ's Anti-Bodies forces. Having nowhere to go, she seeks refuge in a warehouse where she meets Shuu Ouma—a socially awkward high school student who is a huge fan of her music.\n" +
                "\n" +
                "Shuu gets dragged into the conflict the moment he rescues Inori, and the Void Genome shatters in his hand, granting him the \"Power of the Kings.\" While learning how to control his grand new ability, Shuu must now fight to liberate Japan from its cruel oppressors."),
        Anime(9, "Code Geass: Lelouch of the Rebellion ", R.drawable.codegeas, "In the year 2010, the Holy Empire of Britannia is establishing itself as a dominant military nation, starting with the conquest of Japan. Renamed to Area 11 after its swift defeat, Japan has seen significant resistance against these tyrants in an attempt to regain independence.\n" +
                "\n" +
                "Lelouch Lamperouge, a Britannian student, unfortunately finds himself caught in a crossfire between the Britannian and the Area 11 rebel armed forces. He is able to escape, however, thanks to the timely appearance of a mysterious girl named C.C., who bestows upon him Geass, the \"Power of Kings.\" Realizing the vast potential of his newfound \"power of absolute obedience,\" Lelouch embarks upon a perilous journey as the masked vigilante known as Zero, leading a merciless onslaught against Britannia in order to get revenge once and for all."),
        Anime(10, "Tokyo Ghoul", R.drawable.ghoul, "A sinister threat is invading Tokyo: flesh-eating \"ghouls\" who appear identical to humans and blend into their population. Reserved college student Ken Kaneki buries his nose in books and avoids the news of the growing crisis. However, the appearance of an attractive woman named Rize Kamishiro shatters his solitude when she forwardly asks him on a date.\n" +
                "\n" +
                "While walking Rize home, Kaneki discovers she isn't as kind as she first appeared, and she has led him on with sinister intent. After a tragic struggle, he later awakens in a hospital to learn his life was saved by transplanting the now deceased Rize's organs into his own body.\n" +
                "\n" +
                "Kaneki's body begins to change in horrifying ways, and he transforms into a human-ghoul hybrid. As he embarks on his new dreadful journey, Kaneki clings to his humanity in the evolving bloody conflict between society's new monsters and the government agents who hunt them.")
    )
}